# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpost',
            name='slug',
            field=models.SlugField(),
        ),
    ]
