# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-15 01:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20170214_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bpost',
            name='slug',
        ),
    ]
