# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-02-19 00:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_remove_bpost_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='bpost',
            name='user_created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
