"""
Django settings for trydjangoblog project.

Generated by 'django-admin startproject' using Django 1.9.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
#BASE_DIR = Project directory
#print(BASE_DIR) --> C:/users/Mark Account/dev/trydjango1_9/src
#trydjango1_9 = python virtual environment folder, src = project folder
#because it nests .dirname twice, it gets /src
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '75mmes89ddl0gy@*%f2wu&_#lmfsqhuiqnja563dz6n$^y-(9j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'posts'
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'trydjangoblog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trydjangoblog.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

#its a URL, not a path, its a prefix url, that will be used when referring to the static files in STATIC_ROOT
#can be relative or absolute
STATIC_URL = '/static/'



#STATIC_ROOT = The absolute path to the directory where collectstatic will put/collect/aggregate static files for deployment.
#so when do collectstatic, it aggregates all your app's static files into this one folder, ready to be served by a server
#path is the parent folder of BASE_DIR, + staticCDN. so will = C:/users/Mark Account/dev/trydjango1_9/staticCDN
STATIC_ROOT = os.path.join(os.path.dirname(BASE_DIR), "staticCDN")


#added this:
MEDIA_URL = '/media/'

#folder where user uploads are stored
#path is the parent folder of BASE_DIR, + mediaCDN. so will = C:/users/Mark Account/dev/trydjango1_9/mediaCDN
MEDIA_ROOT = os.path.join(os.path.dirname(BASE_DIR), "mediaCDN")


#var list the ADDITIONAL locations that collectstatic will search.
#so django will collect static files in app folders, but will ALSO look here:
# Put strings here, like "/home/html/static" or "C:/www/django/static".
# Don't forget to use absolute paths, not relative paths.
#Inour case, it Holds static files that are not app unique, but project wide.
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"), #
]
